### ISSUE TITLE
love the pack but..

### ISSUE THREAD

**Issue by hedron2003** [rpayne19/FFXI_to_FFVI_Font_Mod#1]
i love the pack but is there any way to have the maqcro pallette background be black instead of blue?? hell ill learn to do it myself if i can just get pointed in right direction to do it..

**Comment by rpayne19** [comment]
Thanks for the feedback. I just saw your post on youtube as well from 6 months ago. For some reason youtube does not always notify me when there's a post, however, github sure does.

Regarding the macro palette, I'm sure it's possible, but would take some time to find the graphics asset to change. One downside to this is the possibility that the user would want a matching palette color that corresponds to the rest of their menus. So a solution might be to have all the menus black in one dat release, and have them be the default in another.

Regarding your other comment about just the fonts... you may have to be more specific about this. In the process of making these mod, you'd think that I should just be able to update a font and go... there's actually a number of images, some containing different bitmap fonts, stored in a single dat file. The developers of FFXI decided that they wanted different fonts all over the place and used them each in one or many places.

If, for example, you just wanted the font to be in the chat window, that would be doable. But if you wanted the font also in the party status box (bottom right of the screen) but not the status menus and the names above characters heads, that would not be doable since the game references the same bitmap font for all of those. Based on that, if that's still something you'd like, please open another issue w/ more details here on this githup repo.
